apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-job
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-job
  template:
    metadata:
      labels:
        name: cluster-job
    spec:
      serviceAccountName: cluster-job
      containers:
        - name: cluster-job
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cluster-job
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-job"
